---
name: Secrets Scan

"on":
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # v6.0.2
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        # master
        uses: gitleaks/gitleaks-action@bf2dc8e55639c1e091e9b45970152e4313705814
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
